# Copyright (c) 2016-present Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (c) 2016-present Sven Greb <development@svengreb.de>

# Project:    igloo
# Repository: https://github.com/arcticicestudio/igloo
# License:    MIT

# Configuration for lazydocker.
# See:
#   1. https://github.com/jesseduffield/lazydocker/blob/master/docs/Config.md
#   2. https://github.com/jesseduffield/lazydocker/blob/master/docs/keybindings/Keybindings_en.md
#   3. https://pkg.go.dev/github.com/jesseduffield/lazydocker/pkg/config

customCommands:
  services:
    # Run a single service in detached mode.
    - name: up-detached
      attach: false
      command: "{{ .DockerCompose }} up --detach {{ .Service.Name }}"
    # Stop, if required, and remove all containers and volumnes of a service.
    - name: wipe
      command: "{{ .DockerCompose }} rm --stop --force -v {{ .Service.Name }}"

gui:
  showAllContainers: true
  returnImmediately: true
  theme:
    activeBorderColor:
      - cyan
    inactiveBorderColor:
      - black
      - bold
    optionsTextColor:
      - blue

reporting: "off"
