#!/usr/bin/env bash
# Copyright (c) 2016-2017 Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (c) 2016-2017 Sven Greb <code@svengreb.de>

# Project:    igloo
# Repository: https://github.com/arcticicestudio/igloo
# License:    MIT

# GPG decryption command for the "igloocrypt" diff filter
# The output is redirected to suppress error messages caused by the Git filter flow.

gpg --decrypt --batch --no-tty "$1" > /dev/null 2>&1 || cat $1
