#!/usr/bin/env bash

# Copyright (C) 2016-present Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (C) 2016-present Sven Greb <development@svengreb.de>

# Project:    igloo
# Repository: https://github.com/arcticicestudio/igloo
# License:    MIT

# Switch up as many parent directories as the pass number.
# Goes up one by default if no parameter is passed.
#
# @param $1 the amount of parent directories to switch up
..() {
  local d=""
  limit=$1
  for ((i=1 ; i <= limit ; i++)); do
    d=$d/..
  done
  d=$(echo $d | sed 's/^\///')
  if [[ -z "$d" ]]; then
    d=..
  fi
  cd $d
  return 0
}

# Extract archived files.
#
# @param $1 the file to extract
# @throws 1 Unsupported or invalid file
extract() {
  if [ -f $1 ]; then
    case $1 in
      *.tar.bz2) tar -jxvf $1 ;;
      *.tar.gz)  tar -zxvf $1 ;;
      *.bz2)     bunzip2 $1 ;;
      *.gz)      gunzip $1 ;;
      *.tar)     tar -xvf $1 ;;
      *.tbz2)    tar -jxvf $1 ;;
      *.tgz)     tar -zxvf $1 ;;
      *.zip)     unzip $1 ;;
      *)
      printf "\e[33mUnsupported format\e[0m"
      return 1
      ;;
    esac
    printf "\e[32mExtracted\e[0m %s" "$1"
  else
    printf "\e[33m%s is not a valid extractable file\e[0m" "$1"
    return 1
  fi
  return 0
}

# Extracts archived files to the specified destination.
# Append a 'v' character at the end to be verbose.
#
# @param $1 the file to extract
# @param $2 (optional) the extraction destination path
# @param $3 flag to indicate verbosity level
# @options ["v"]
# @throws 1 No arguments
# @throws 2 File not found
# @throws 3 Invalid user input
# @throws 4 Invalid option
# @throws 5 Unsupported file format
# @throws 6 Write permission error
extractto() {
  local isVerbose destination response filename

  trap "echo User aborted." SIGINT SIGTERM

  if [[ "$#" -lt 1 ]]; then
    printf "\e[1mUsage: \e[36mextractto \e[01;36m<FILE> \e[30m[DESTINATION_FOLDER] [v]\e[0m\n"
    printf "Append a \e[36mv\e[0m to be verbose"
    return 1
  fi

  if [[ ! -e "$1" ]]; then
    printf "\e[31mFile not found\e[0m"
    return 2
  fi

  if [[ -z "$2" ]]; then
    destination="."
  elif [[ ! -d "$2" ]]; then
    printf "\e[33mDestination folder not exist or is not a directory.\e[0m"
    printf "\nCreate? (y/n): "
    read response
    if [[ $response == y || $response == Y ]]; then
      mkdir -p "$2"
      if [ $? -eq 0 ]; then
        destination="$2"
      else
        return 6
      fi
    else
      return 3
    fi
  else
    destination="$2"
  fi

  if [[ ! -z "$3" ]]; then
    if [[ "$3" != "v" ]]; then
      printf "\e[31mWrong argument %s\e[0m" "$3"
      return 4
    fi
    isVerbose="$3"
  fi

  filename=`basename "$1"`

  case "${filename##*.}" in
    tar)
      tar x${isVerbose}f "$1" -C "$destination"
      printf "\e[36m%s\e[0m > \e[36m%s\e[0m (uncompressed tar)" "$1" "$destination"
      ;;
    gz)
      tar x${isVerbose}fz "$1" -C "$destination"
      printf "\e[36m%s\e[0m > \e[36m%s\e[0m (gzip compressed tar)" "$1" "$destination"
      ;;
    tgz)
      tar x${isVerbose}fz "$1" -C "$destination"
      printf "\e[36m%s\e[0m > \e[36m%s\e[0m (gzip compressed tar)" "$1" "$destination"
      ;;
    xz)
      tar x${isVerbose}f -J "$1" -C "$destination"
      printf "\e[36m%s\e[0m > \e[36m%s\e[0m (gzip compressed tar)" "$1" "$destination"
      ;;
    bz2)
      tar x${isVerbose}fj "$1" -C "$destination"
      printf "\e[36m%s\e[0m > \e[36m%s\e[0m (bzip compressed tar)" "$1" "$destination"
      ;;
    zip)
      unzip "$1" -d "$destination"
      printf "\e[36m%s\e[0m > \e[36m%s\e[0m (zip compressed tar)" "$1" "$destination"
      ;;
    rar)
      unrar x "$1" "$destination"
      printf "\e[36m%s\e[0m > \e[36m%s\e[0m (rar compressed file)" "$1" "$destination"
      ;;
    7z)
      7za e "$1" -o"$destination"
      printf "\e[36m%s\e[0m > \e[36m%s\e[0m (7zip compressed file)" "$1" "$destination"
      ;;
    *)
      printf "\e[33mUnsupported file format\e[0m"
      return 5
      ;;
  esac

  trap '' SIGINT SIGTERM
  return 0
}

# Compress files into archives.
#
# @param $1 the name of the archive
# @param $2 the paths(s)/file(s) to compress
# @throws 1 Unsupported or invalid file
compress() {
  if [ -n $1 ]; then
    file=$1
    case $file in
      *.tar.xz) shift && tar cJf $file $* ;;
      *.tar.bz2) shift && tar cjf $file $* ;;
      *.tar.gz) shift && tar czf $file $* ;;
      *.gz) shift && tar czf $file $* ;;
      *.tar) shift && tar cf $file $* ;;
      *.tgz) shift && tar czf $file $* ;;
      *.zip) shift && zip $file $* ;;
      *.7z) shift && 7za a $file $* >/dev/null ;;
      *)
        echo -e "\e[1;38;5;221m\u2757 \e[0mUnsupported format"
        return 1
        ;;
    esac
    echo -e "\e[1;38;5;77m\u2714 \e[0mCompressed \e[3;38;5;80m'$file'\e[0m"
  else
    echo -e "\e[1;38;5;160m\u2717 \e[3;38;5;80m'$file' \e[1;37mis not a valid extractable file\e[0m"
    return 1
  fi
  return 0
}

# Shows the current session time.
# Use option "-s" to show the session start.
#
# @param $@ (optional) the options
# @options ["-s","-h"]
# @throws 1 Unknown option
seti() {
  local uptime session
  session=0

  case "$1" in
    -s)
      session=1
      ;;
    -h)
      printf "\e[1mUsage: \e[36mseti \e[30m[OPTIONS]\n"
      printf "  \e[01;36m-s  \e[0mShow session start\n"
      printf "  \e[01;36m-h  \e[0mShow this help\e[0m\n"
      return 0
      ;;
    -*)
      printf "\e[31mUnknown option\e[0m"
      return 1
      ;;
  esac

  if [ $session -gt 0 ]
  then
    uptime=$(uptime -s)
  else
    uptime=$(</proc/uptime)
    uptime=${uptime%%.*}

    s=$(( uptime%60 ))
    m=$(( uptime/60%60 ))
    h=$(( uptime/60/60%24 ))
    d=$(( uptime/60/60/24 ))

    uptime=""$d"d "$h"h "$m"m "$s"s"
  fi
  printf "\e[36m%s\e[0m" "$uptime"
  return 0
}

# Create a new directory and enter it.
#
# @param $1 the name of the directory to create and enter
mkd() {
  mkdir -p "$@" && cd "$@"
}

# Compare original and gzipped file size.
#
# @param $1 the file to compare
gzcomp() {
  local origsize=$(wc -c < "$1");
  local gzipsize=$(gzip -c "$1" | wc -c);
  local ratio=$(echo "$gzipsize * 100 / $origsize" | bc -l);
  printf "orig: %d bytes\n" "$origsize";
  printf "gzip: %d bytes (%2.2f%%)\n" "$gzipsize" "$ratio";
}

# Encode a string of Unicode symbols to UTF-8
#
# @param $1 the string to escape
uesc() {
  printf "\\\x%s" $(printf "$@" | xxd -p -c1 -u);
}
