#!/usr/bin/env bash

# Copyright (C) 2016-present Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (C) 2016-present Sven Greb <development@svengreb.de>

# Project:    igloo
# Repository: https://github.com/arcticicestudio/igloo
# License:    MIT
# References:
#   dircolors(1)
#   dir_colors(5)

[[ -e ~/.dir_colors ]] && eval $(dircolors ~/.dir_colors)
