#!/usr/bin/env bash

# Copyright (C) 2016-present Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (C) 2016-present Sven Greb <development@svengreb.de>

# Project:    igloo
# Repository: https://github.com/arcticicestudio/igloo
# License:    MIT

# Configures the Go development environment.
#
# @see https://golang.org/doc/code.html#GOPATH
# @see https://github.com/golang/go/wiki/GOPATH
# @see https://github.com/golang/go/wiki/SettingGOPATH

export GOPATH="$HOME/.go"
