#!/usr/bin/env bash
# Copyright (c) 2016-2017 Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (c) 2016-2017 Sven Greb <code@svengreb.de>

# Project:    igloo
# Repository: https://github.com/arcticicestudio/igloo
# License:    MIT
# References:
#   https://docs.gradle.org/current/userguide/gradle_command_line.html
#   https://docs.gradle.org/current/userguide/build_environment.html
#   https://docs.gradle.org/current/userguide/console.html#sec:console_build_output

# Set the default system-wide Gradle options.
#
# > org.gradle.daemon
#   Enable to always use the Gradle daemon to run builds.
#   Since Gradle 3.0, daemon is enabled by default and is recommended for running Gradle.
# > org.gradle.console
#   Use "rich" level to always colorize console output.
export GRADLE_OPTS="-Dorg.gradle.daemon=true -Dorg.gradle.console=rich"
