#!/usr/bin/env bash

# Copyright (C) 2016-present Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (C) 2016-present Sven Greb <development@svengreb.de>

# Project:    igloo
# Repository: https://github.com/arcticicestudio/igloo
# License:    MIT
# References:
#   http://gulpjs.com
#   https://github.com/gulpjs/gulp-cli#completion
#   https://github.com/gulpjs/gulp

eval "$(gulp --completion=bash)"
