#!/usr/bin/env bash
# Copyright (c) 2016-2017 Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (c) 2016-2017 Sven Greb <code@svengreb.de>

# Project:    igloo
# Repository: https://github.com/arcticicestudio/igloo
# License:    MIT
# References:
#   http://gulpjs.com
#   https://github.com/gulpjs/gulp-cli#completion
#   https://github.com/gulpjs/gulp

eval "$(gulp --completion=bash)"
