#!/usr/bin/env bash
# Copyright (c) 2016-2017 Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (c) 2016-2017 Sven Greb <code@svengreb.de>

# Project:    igloo
# Repository: https://github.com/arcticicestudio/igloo
# License:    MIT
# References:
#   terminfo(5)
#   http://www.iso.org/iso/home/standards/iso8601.htm

# +--------+
# + Output +
# +--------+
# Sets the amount of entries to be unlimited.
export HISTSIZE=""

# Sets the filesize to be unlimited.
export HISTFILESIZE=""

# +--------+
# + Format +
# +--------+
# Use ISO-8681 time format.
export HISTTIMEFORMAT="[%Y-%m-%d %H:%M:%S UTC%z] "

# Define commands that should be ignored.
# The commands must be separated by a double point and include the exact option- and flag parameters!
export HISTIGNORE="pwd:ls:ls -ltr:ls -lAhF:cd ..:.."

# Sets the control filter.
#
# "ignoredups"
#   Ignores duplicates
# "ignorespace"
#   Ignores commands beginning with a space character
# "ignoreboth"
#   Implies "ignoredups" and "ignorespace"
# "erasedups"
#   Erase duplicates across the whole history
export HISTCONTROL="ignoreboth"
