#!/usr/bin/env bash
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++
# title      Java Configuration                        +
# project    igloo                                     +
# repository https://github.com/arcticicestudio/igloo  +
# author     Arctic Ice Studio                         +
# email      development@arcticicestudio.com           +
# copyright  Copyright (C) 2017                        +
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++
#
# [References]
# StackOverflow
#   (http://stackoverflow.com/questions/28327620/difference-between-java-options-java-tool-options-and-java-opts)
# Oracle JDK 8
#   (http://docs.oracle.com/javase/8/docs/technotes/guides/2d/flags.html#aaFonts)
#   (http://docs.oracle.com/javase/8/docs/technotes/guides/2d/flags.html#xrender)
# NetBeans Wiki
#   (http://wiki.netbeans.org/FaqFontRendering)
# java(1)
# javac(1)

# Sets the default system-wide JVM options.
#
# "-Dawt.useSystemAAFontSettings"
#   Use system settings for font anti-aliasing.
# "-Dsun.java2d.xrender"
#   Enable the XRender-based Java 2D rendering pipeline for modern X11-based desktops, offering improved graphics
#   performance.
# "-Dswing.aatext"
#   Enable the font anti-aliasing for Swing-based applications.
#
# Constant names in braces are values for the "java.awt.RenderingHint" class.
#
# > awt.useSystemAAFontSettings
#   "off" | "false" | "default" ("VALUE_TEXT_ANTIALIAS_DEFAULT")
#     No anti-aliasing.
#   "on" ("VALUE_TEXT_ANTIALIAS_ON")
#     Full anti-aliasing without sub-pixel rendering
#   "gasp" ("VALUE_TEXT_ANTIALIAS_GASP")
#     Use the font's built-in hinting instructions with sub-pixel rendering, intended for use both on CRT and LCD .
#   "lcd" | "lcd_hrgb" ("VALUE_TEXT_ANTIALIAS_LCD_HRGB")
#     Anti-aliasing tuned for many popular LCD monitors with sub-pixel rendering, optimized for LCD.
#   "lcd_hbgr" ("VALUE_TEXT_ANTIALIAS_LCD_HBGR")
#     Alternative LCD monitor setting. Same as "lcd", but with different distribution of sub pixels (monitor upside
#     down).
#   "lcd_vrgb" ("VALUE_TEXT_ANTIALIAS_LCD_VRGB")
#     Alternative LCD monitor setting. Same as "lcd", but with different distribution of sub pixels (monitor is
#     vertical).
#   "lcd_vbgr" ("VALUE_TEXT_ANTIALIAS_LCD_VBGR")
#     Alternative LCD monitor setting. Same as "lcd", but with different distribution of sub pixels (vertical again but
#     on other side).
export _JAVA_OPTIONS="-Dawt.useSystemAAFontSettings=lcd -Dsun.java2d.xrender=true -Dswing.aatext=true"
