#!/usr/bin/env bash
# Copyright (c) 2016-2017 Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (c) 2016-2017 Sven Greb <code@svengreb.de>

# Project:    igloo
# Repository: https://github.com/arcticicestudio/igloo
# License:    MIT
# References:
#   https://github.com/rmarquis/pacaur

export AURDEST=/tmp/pacaur/cache
