#!/usr/bin/env bash

# Copyright (C) 2016-present Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (C) 2016-present Sven Greb <development@svengreb.de>

# Project:    igloo
# Repository: https://github.com/arcticicestudio/igloo
# License:    MIT
# References:
#   sudo(8)

export SUDO_PROMPT=$(printf "\e[01;30;47msudo\e[0m \e[36m%%u\e[0m@\e[34m%%h\e[m: ")
